In [72]:
import cv2
import numpy as np

In [93]:
#1- Read the road.jpg image using OpenCV. Print it to the screen.

im = cv2.imread('road.jpg')
imS = cv2.resize(im, (960, 540))  #i resized the image only for the purpose of viewing it since it was too big

cv2.imshow('image1',imS)
cv2.waitKey(7000)
cv2.destroyWindow('image1')

In [94]:
#2- Print the shape of your image. What are the high, width, and number of the channels?

h,w,c = im.shape
print('Height,Width of image =', im.shape[:2], 'and # of channels = ', c)

Height,Width of image = (1603, 2400) and # of channels =  3


In [95]:
#3- Read the image as a grayscale, then print the shape. Is there a difference in the result? 

im_gray = cv2.imread('road.jpg',0)
imgray = cv2.resize(im_gray, (960, 540))  #i resized the image only for the purpose of viewing it since it was too big

cv2.imshow('image1',imgray)
cv2.waitKey(7000)
cv2.destroyWindow('image1')

im_gray.shape


#the difference is that a grayscale image has one channel, while RGB images have 3 channels, so the shape for grayscale images is just (height,width)
#while the shape for RGB images is (height,width,3)

(1603, 2400)

In [96]:
#4- Slice/crop the white biggest truck in the image and show the cropped image, print the pixel intensities values of the cropped ROI, 
#then change its pixel values to 0, attach the new value to the old image, and print the modified one.

cropped_im = im[900:1603, 1:600] 
cv2.imshow('cropped image',cropped_im)

cv2.waitKey(4000)
cv2.destroyAllWindows()

print('pixel intensities values:\n',cropped_im) 


pixel intensities values:
 [[[ 17  34  37]
  [ 20  35  38]
  [ 22  37  40]
  ...
  [108 102 121]
  [108 100 123]
  [106 100 123]]

 [[ 18  35  38]
  [ 22  37  40]
  [ 24  39  42]
  ...
  [106 100 119]
  [105  97 120]
  [102  96 119]]

 [[ 19  36  39]
  [ 24  39  42]
  [ 27  42  45]
  ...
  [103  97 116]
  [101  93 116]
  [ 97  91 114]]

 ...

 [[ 65  51  53]
  [ 68  51  55]
  [ 67  52  56]
  ...
  [ 66  58  69]
  [ 66  58  69]
  [ 66  58  69]]

 [[ 67  51  52]
  [ 68  51  54]
  [ 69  52  55]
  ...
  [ 66  58  69]
  [ 66  58  69]
  [ 66  58  69]]

 [[ 67  51  52]
  [ 68  51  54]
  [ 69  52  55]
  ...
  [ 66  58  69]
  [ 66  58  69]
  [ 66  58  69]]]


In [97]:
im[900:1603, 1:600] = np.zeros(cropped_im.shape)

imS = cv2.resize(im, (960, 540))  #i resized the image only for the purpose of viewing it since it was too big
cv2.imshow("cropped1", imS)

cv2.waitKey(10000)
cv2.destroyAllWindows()

In [99]:
#5- Resize the image by 0.5, then rotate it by 45 degrees clockwise, and show the result.

sf = 0.5
scaled_im = cv2.resize(im, None, fx = sf, fy = sf)

height, width = scaled_im.shape[:2]
center = (width/2, height/2)

rot_sim = cv2.getRotationMatrix2D(center=center, angle= -45, scale=1)

rotated_im = cv2.warpAffine(src=scaled_im, M=rot_sim, dsize=(width, height))

cv2.imshow('scaled image', scaled_im)
cv2.imshow('Rotated image', rotated_im)
cv2.waitKey(16000)
cv2.destroyAllWindows()